const SKILLS = {
  Languages: [
    'TypeScript',
    'JavaScript',
    'Python',
    'Java',
    'C',
    'C++',
    'C#',
    'Swift',
    'Smalltalk',
    'SQL',
    'Scheme',
    'Prolog',
    'Solidity',
    'Rust',
    'HTML',
    'CSS',
    'XML',
    'LaTex',
    'Yaml',
    'GraphQL',
  ],
  'Frameworks & Libraries': [
    'Node.js',
    'Deno',
    'React',
    'React Native',
    'Angular',
    'Django',
    'Flask',
    'Express',
    'Fastify',
    'Blitz.js',
    'Next.js',
    'Gatsby.js',
    'TailwindCSS',
    'CSS in JS',
    'Material UI',
    'Cloudflare Workers',
  ],
  Datastores: [
    'MongoDB',
    'SQLite',
    'MySQL',
    'PostgreSQL',
    'Redis',
    'Cloudflare KV',
  ],
  Ops: [
    'Docker',
    'Docker Compose',
    'Kubernetes',
    'Apache',
    'Nginx',
    'Azure',
    'Google Cloud',
    'AWS',
  ],
  'CI/CD': [
    'GitHub Actions',
    'GitLab CI',
    'Travis CI',
    'Circle CI',
    'Bitrise',
    'Netlify',
    'Vercel',
    'Gatsby Cloud',
  ],
  Tools: [
    'Jira',
    'GitHub Projects',
    'GitLab',
    'Xcode',
    'Intelij Rider',
    'Intelij PyCharm',
    'Visual Studio',
    'Visual Studio Code',
    'VIM',
  ],
}

export default SKILLS
